"""create core domain schema

Revision ID: 0001
Revises:
Create Date: 2026-09-05 10:17:12.596163
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(slug) >= 2", name=op.f("ck_organizations_slug_length")),
        sa.CheckConstraint("slug = lower(slug)", name=op.f("ck_organizations_slug_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "tool_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_name", sa.String(length=150), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("contract_hash", sa.String(length=64), nullable=False),
        sa.Column("business_semantics", sa.Text(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "READ_ONLY",
                "LOW_RISK_WRITE",
                "APPROVAL_REQUIRED",
                "FORBIDDEN",
                name="tool_risk_level",
            ),
            nullable=False,
        ),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("authorization_policy_version", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "contract_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_tool_definitions_contract_hash_sha256"),
        ),
        sa.CheckConstraint(
            "stable_name = lower(stable_name)",
            name=op.f("ck_tool_definitions_stable_name_lowercase"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_definitions")),
        sa.UniqueConstraint("stable_name", "schema_version", name="uq_tool_definitions_contract"),
    )
    op.create_table(
        "target_systems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("system_key", sa.String(length=100), nullable=False),
        sa.Column("system_type", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column(
            "configuration_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "system_key = lower(system_key)", name=op.f("ck_target_systems_system_key_lowercase")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_target_systems_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_systems")),
        sa.UniqueConstraint("organization_id", "id", name="uq_target_systems_scope_id"),
        sa.UniqueConstraint("organization_id", "system_key", name="uq_target_systems_scope_key"),
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL_DOC",
                "OFFICIAL_REPOSITORY",
                "PUBLIC_ISSUE",
                "INTERNAL_RUNBOOK",
                "SYNTHETIC",
                name="knowledge_source_type",
            ),
            nullable=False,
        ),
        sa.Column("source_locator", sa.Text(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("ORGANIZATION", "PUBLIC", name="knowledge_visibility"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_knowledge_documents_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_documents_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
        sa.UniqueConstraint(
            "organization_id", "target_system_id", "id", name="uq_knowledge_documents_scope_id"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "source_key",
            name="uq_knowledge_documents_scope_source",
        ),
    )
    op.create_table(
        "provider_catalog_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum("MCP", "REST", "PROBE", "INTERNAL", name="provider_type"),
            nullable=False,
        ),
        sa.Column("endpoint_identifier", sa.String(length=200), nullable=False),
        sa.Column("catalog_hash", sa.String(length=64), nullable=False),
        sa.Column("observed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "catalog_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_provider_catalog_snapshots_catalog_hash_sha256"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(observed_tools) = 'array'",
            name=op.f("ck_provider_catalog_snapshots_observed_tools_array"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_provider_catalog_snapshots_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_provider_catalog_snapshots_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_catalog_snapshots")),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "id",
            name="uq_provider_catalog_snapshots_scope_id",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "provider_type",
            "endpoint_identifier",
            "catalog_hash",
            name="uq_provider_catalog_snapshots_observation",
        ),
    )
    op.create_table(
        "retrieval_index_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("index_key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("BUILDING", "READY", "FAILED", "RETIRED", name="retrieval_index_status"),
            nullable=False,
        ),
        sa.Column("chunking_version", sa.String(length=100), nullable=False),
        sa.Column("dense_model", sa.String(length=200), nullable=False),
        sa.Column("dense_version", sa.String(length=100), nullable=False),
        sa.Column("dense_dimensions", sa.SmallInteger(), nullable=False),
        sa.Column("sparse_model", sa.String(length=200), nullable=False),
        sa.Column("sparse_version", sa.String(length=100), nullable=False),
        sa.Column("exact_match_version", sa.String(length=100), nullable=False),
        sa.Column(
            "fusion_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "reranker_configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "configuration_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_retrieval_index_versions_config_hash_sha256"),
        ),
        sa.CheckConstraint(
            "dense_dimensions = 1024",
            name=op.f("ck_retrieval_index_versions_dense_dimensions_1024"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_retrieval_index_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_retrieval_index_versions_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_retrieval_index_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_index_versions")),
        sa.UniqueConstraint(
            "organization_id", "target_system_id", "id", name="uq_retrieval_index_versions_scope_id"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "index_key",
            "version",
            name="uq_retrieval_index_versions_key_version",
        ),
    )
    op.create_table(
        "tool_provider_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("tool_definition_id", sa.Uuid(), nullable=False),
        sa.Column("fallback_binding_id", sa.Uuid(), nullable=True),
        sa.Column("binding_key", sa.String(length=150), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("binding_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum("MCP", "REST", "PROBE", "INTERNAL", name="provider_type"),
            nullable=False,
        ),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("endpoint_identifier", sa.String(length=200), nullable=False),
        sa.Column("upstream_tool_name", sa.String(length=200), nullable=False),
        sa.Column("catalog_hash", sa.String(length=64), nullable=True),
        sa.Column("input_transform_version", sa.String(length=100), nullable=False),
        sa.Column("output_transform_version", sa.String(length=100), nullable=False),
        sa.Column(
            "health_scope",
            sa.Enum(
                "CONNECTOR", "APPLICATION", "RUNTIME_COMPONENT", "BUSINESS_JOB", name="health_scope"
            ),
            nullable=False,
        ),
        sa.Column(
            "health_condition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "binding_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_tool_provider_bindings_binding_hash_sha256"),
        ),
        sa.CheckConstraint(
            "catalog_hash IS NULL OR catalog_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_tool_provider_bindings_catalog_hash_sha256"),
        ),
        sa.CheckConstraint(
            "provider_type <> 'MCP' OR catalog_hash IS NOT NULL",
            name=op.f("ck_tool_provider_bindings_mcp_catalog_hash_required"),
        ),
        sa.CheckConstraint(
            "priority >= 0", name=op.f("ck_tool_provider_bindings_priority_nonnegative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tool_provider_bindings_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "fallback_binding_id"],
            [
                "tool_provider_bindings.organization_id",
                "tool_provider_bindings.target_system_id",
                "tool_provider_bindings.id",
            ],
            name="fk_tool_provider_bindings_scope_fallback",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_tool_provider_bindings_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tool_provider_bindings_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"],
            ["tool_definitions.id"],
            name=op.f("fk_tool_provider_bindings_tool_definition_id_tool_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_provider_bindings")),
        sa.UniqueConstraint(
            "organization_id", "target_system_id", "id", name="uq_tool_provider_bindings_scope_id"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "id",
            "tool_definition_id",
            name="uq_tool_provider_bindings_scope_tool",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "tool_definition_id",
            "binding_key",
            "version",
            name="uq_tool_provider_bindings_version",
        ),
    )
    op.create_index(
        "ix_tool_provider_bindings_resolution",
        "tool_provider_bindings",
        ["organization_id", "target_system_id", "tool_definition_id", "priority"],
        unique=False,
        postgresql_where=sa.text("enabled"),
    )
    op.create_table(
        "knowledge_document_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("license_or_terms", sa.String(length=500), nullable=True),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "target_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("acquisition_method", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_knowledge_document_versions_content_hash_sha256"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_knowledge_document_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "document_id"],
            [
                "knowledge_documents.organization_id",
                "knowledge_documents.target_system_id",
                "knowledge_documents.id",
            ],
            name="fk_knowledge_document_versions_scope_document",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_document_versions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_document_versions")),
        sa.UniqueConstraint(
            "document_id", "version", name="uq_knowledge_document_versions_version"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "id",
            name="uq_knowledge_document_versions_scope_id",
        ),
    )
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("tool_definition_id", sa.Uuid(), nullable=False),
        sa.Column("provider_binding_id", sa.Uuid(), nullable=False),
        sa.Column("provider_catalog_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("stable_tool_name_snapshot", sa.String(length=150), nullable=False),
        sa.Column("tool_schema_version_snapshot", sa.String(length=50), nullable=False),
        sa.Column(
            "provider_type_snapshot",
            sa.Enum("MCP", "REST", "PROBE", "INTERNAL", name="provider_type"),
            nullable=False,
        ),
        sa.Column("binding_key_snapshot", sa.String(length=150), nullable=False),
        sa.Column("binding_version_snapshot", sa.Integer(), nullable=False),
        sa.Column("upstream_tool_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("request_correlation_id", sa.String(length=200), nullable=True),
        sa.Column("fallback_reason", sa.String(length=500), nullable=True),
        sa.Column("authorization_scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("STARTED", "SUCCEEDED", "FAILED", "REJECTED", name="tool_execution_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.SmallInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_tool_executions_finished_after_started"),
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_tool_executions_retry_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "target_system_id",
                "provider_binding_id",
                "tool_definition_id",
            ],
            [
                "tool_provider_bindings.organization_id",
                "tool_provider_bindings.target_system_id",
                "tool_provider_bindings.id",
                "tool_provider_bindings.tool_definition_id",
            ],
            name="fk_tool_executions_scope_binding",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "provider_catalog_snapshot_id"],
            [
                "provider_catalog_snapshots.organization_id",
                "provider_catalog_snapshots.target_system_id",
                "provider_catalog_snapshots.id",
            ],
            name="fk_tool_executions_scope_catalog",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_tool_executions_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tool_executions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"],
            ["tool_definitions.id"],
            name=op.f("fk_tool_executions_tool_definition_id_tool_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
        sa.UniqueConstraint(
            "organization_id", "target_system_id", "id", name="uq_tool_executions_scope_id"
        ),
    )
    op.create_index(
        "ix_tool_executions_scope_started",
        "tool_executions",
        ["organization_id", "target_system_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "uq_tool_executions_idempotency",
        "tool_executions",
        ["organization_id", "stable_tool_name_snapshot", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("tool_execution_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum("SYSTEM", "USER", "AGENT", name="audit_actor_type"),
            nullable=False,
        ),
        sa.Column("actor_ref", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=150), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=200), nullable=False),
        sa.Column("correlation_id", sa.String(length=200), nullable=True),
        sa.Column("payload_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "payload_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_audit_events_payload_hash_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "tool_execution_id"],
            [
                "tool_executions.organization_id",
                "tool_executions.target_system_id",
                "tool_executions.id",
            ],
            name="fk_audit_events_scope_tool_execution",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id"],
            ["target_systems.organization_id", "target_systems.id"],
            name="fk_audit_events_scope_target",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_entity", "audit_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_scope_occurred",
        "audit_events",
        ["organization_id", "target_system_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("target_system_id", sa.Uuid(), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("retrieval_index_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_chunk_id", sa.Uuid(), nullable=True),
        sa.Column(
            "chunk_kind", sa.Enum("PARENT", "CHILD", name="knowledge_chunk_kind"), nullable=False
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("structure_path", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column(
            "structure_unit_type",
            sa.Enum(
                "PROSE",
                "CODE_BLOCK",
                "CONFIGURATION",
                "TABLE",
                "PROCEDURE",
                "HEADING",
                name="structure_unit_type",
            ),
            nullable=False,
        ),
        sa.Column("source_locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("safe_content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "retrieval_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "representation_status",
            sa.Enum("NOT_APPLICABLE", "PENDING", "READY", "FAILED", name="representation_status"),
            nullable=False,
        ),
        sa.Column("dense_embedding", Vector(1024), nullable=True),
        sa.Column("sparse_weights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding_version", sa.String(length=100), nullable=True),
        sa.Column("sparse_version", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(chunk_kind = 'PARENT' AND parent_chunk_id IS NULL AND representation_status = 'NOT_APPLICABLE' AND dense_embedding IS NULL AND sparse_weights IS NULL AND embedding_version IS NULL AND sparse_version IS NULL) OR (chunk_kind = 'CHILD' AND parent_chunk_id IS NOT NULL AND representation_status IN ('PENDING', 'READY', 'FAILED'))",
            name=op.f("ck_knowledge_chunks_parent_child_representation_shape"),
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_knowledge_chunks_content_hash_sha256")
        ),
        sa.CheckConstraint(
            "representation_status <> 'READY' OR (dense_embedding IS NOT NULL AND sparse_weights IS NOT NULL AND embedding_version IS NOT NULL AND sparse_version IS NOT NULL)",
            name=op.f("ck_knowledge_chunks_ready_representation_complete"),
        ),
        sa.CheckConstraint(
            "sparse_weights IS NULL OR jsonb_typeof(sparse_weights) = 'object'",
            name=op.f("ck_knowledge_chunks_sparse_weights_object"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_knowledge_chunks_ordinal_nonnegative")),
        sa.CheckConstraint(
            "token_count >= 0", name=op.f("ck_knowledge_chunks_token_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "target_system_id",
                "document_version_id",
                "retrieval_index_version_id",
                "parent_chunk_id",
            ],
            [
                "knowledge_chunks.organization_id",
                "knowledge_chunks.target_system_id",
                "knowledge_chunks.document_version_id",
                "knowledge_chunks.retrieval_index_version_id",
                "knowledge_chunks.id",
            ],
            name="fk_knowledge_chunks_scope_parent",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "document_version_id"],
            [
                "knowledge_document_versions.organization_id",
                "knowledge_document_versions.target_system_id",
                "knowledge_document_versions.id",
            ],
            name="fk_knowledge_chunks_scope_document_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "target_system_id", "retrieval_index_version_id"],
            [
                "retrieval_index_versions.organization_id",
                "retrieval_index_versions.target_system_id",
                "retrieval_index_versions.id",
            ],
            name="fk_knowledge_chunks_scope_index_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_knowledge_chunks_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "document_version_id",
            "retrieval_index_version_id",
            "ordinal",
            name="uq_knowledge_chunks_version_ordinal",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "target_system_id",
            "document_version_id",
            "retrieval_index_version_id",
            "id",
            name="uq_knowledge_chunks_scope_id",
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_retrieval_filter",
        "knowledge_chunks",
        [
            "organization_id",
            "target_system_id",
            "retrieval_index_version_id",
            "chunk_kind",
            "representation_status",
        ],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION reject_append_only_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only; create a new record instead', TG_TABLE_NAME
                USING ERRCODE = '23514';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_retrieval_index_version_lifecycle()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'retrieval index versions are immutable'
                    USING ERRCODE = '23514';
            END IF;

            IF (to_jsonb(NEW) - 'status' - 'completed_at')
               IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'completed_at') THEN
                RAISE EXCEPTION 'retrieval index version configuration is immutable'
                    USING ERRCODE = '23514';
            END IF;

            IF OLD.status = 'BUILDING'
               AND NEW.status IN ('READY', 'FAILED')
               AND NEW.completed_at IS NOT NULL THEN
                RETURN NEW;
            END IF;

            IF OLD.status = 'READY'
               AND NEW.status = 'RETIRED'
               AND NEW.completed_at IS NOT DISTINCT FROM OLD.completed_at THEN
                RETURN NEW;
            END IF;

            RAISE EXCEPTION 'invalid retrieval index version lifecycle transition'
                USING ERRCODE = '23514';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_versioned_contract_lifecycle()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION '% history is immutable', TG_TABLE_NAME
                    USING ERRCODE = '23514';
            END IF;

            IF (to_jsonb(NEW) - 'enabled' - 'updated_at')
               IS DISTINCT FROM (to_jsonb(OLD) - 'enabled' - 'updated_at') THEN
                RAISE EXCEPTION '% semantic fields are immutable; create a new version', TG_TABLE_NAME
                    USING ERRCODE = '23514';
            END IF;

            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_knowledge_document_versions_immutable
        BEFORE UPDATE OR DELETE ON knowledge_document_versions
        FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_provider_catalog_snapshots_immutable
        BEFORE UPDATE OR DELETE ON provider_catalog_snapshots
        FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_retrieval_index_versions_lifecycle
        BEFORE UPDATE OR DELETE ON retrieval_index_versions
        FOR EACH ROW EXECUTE FUNCTION validate_retrieval_index_version_lifecycle()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_tool_definitions_lifecycle
        BEFORE UPDATE OR DELETE ON tool_definitions
        FOR EACH ROW EXECUTE FUNCTION validate_versioned_contract_lifecycle()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_tool_provider_bindings_lifecycle
        BEFORE UPDATE OR DELETE ON tool_provider_bindings
        FOR EACH ROW EXECUTE FUNCTION validate_versioned_contract_lifecycle()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_tool_executions_append_only
        BEFORE UPDATE OR DELETE ON tool_executions
        FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation()
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_tool_execution_snapshot()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            expected_stable_name text;
            expected_schema_version text;
            expected_provider_type provider_type;
            expected_binding_key text;
            expected_binding_version integer;
            expected_upstream_tool_name text;
            expected_endpoint_identifier text;
            expected_catalog_hash text;
            catalog_matches boolean;
        BEGIN
            SELECT definition.stable_name,
                   definition.schema_version,
                   binding.provider_type,
                   binding.binding_key,
                   binding.version,
                   binding.upstream_tool_name,
                   binding.endpoint_identifier,
                   binding.catalog_hash
              INTO expected_stable_name,
                   expected_schema_version,
                   expected_provider_type,
                   expected_binding_key,
                   expected_binding_version,
                   expected_upstream_tool_name,
                   expected_endpoint_identifier,
                   expected_catalog_hash
              FROM tool_provider_bindings AS binding
              JOIN tool_definitions AS definition
                ON definition.id = binding.tool_definition_id
             WHERE binding.organization_id = NEW.organization_id
               AND binding.target_system_id = NEW.target_system_id
               AND binding.id = NEW.provider_binding_id
               AND definition.id = NEW.tool_definition_id;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'tool execution must use a binding for the same scope and tool'
                    USING ERRCODE = '23503';
            END IF;

            IF NEW.stable_tool_name_snapshot IS DISTINCT FROM expected_stable_name
               OR NEW.tool_schema_version_snapshot IS DISTINCT FROM expected_schema_version
               OR NEW.provider_type_snapshot IS DISTINCT FROM expected_provider_type
               OR NEW.binding_key_snapshot IS DISTINCT FROM expected_binding_key
               OR NEW.binding_version_snapshot IS DISTINCT FROM expected_binding_version
               OR NEW.upstream_tool_name_snapshot IS DISTINCT FROM expected_upstream_tool_name THEN
                RAISE EXCEPTION 'tool execution snapshot does not match its versioned binding'
                    USING ERRCODE = '23514';
            END IF;

            IF (expected_provider_type = 'MCP' OR expected_catalog_hash IS NOT NULL)
               AND NEW.provider_catalog_snapshot_id IS NULL THEN
                RAISE EXCEPTION 'selected provider binding requires its catalog snapshot'
                    USING ERRCODE = '23514';
            END IF;

            IF NEW.provider_catalog_snapshot_id IS NOT NULL THEN
                SELECT EXISTS (
                    SELECT 1
                      FROM provider_catalog_snapshots AS catalog
                     WHERE catalog.organization_id = NEW.organization_id
                       AND catalog.target_system_id = NEW.target_system_id
                       AND catalog.id = NEW.provider_catalog_snapshot_id
                       AND catalog.provider_type = expected_provider_type
                       AND catalog.endpoint_identifier = expected_endpoint_identifier
                       AND (
                            expected_catalog_hash IS NULL
                            OR catalog.catalog_hash = expected_catalog_hash
                       )
                ) INTO catalog_matches;

                IF NOT catalog_matches THEN
                    RAISE EXCEPTION 'provider catalog snapshot does not match selected binding'
                        USING ERRCODE = '23514';
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_validate_tool_execution_snapshot
        BEFORE INSERT OR UPDATE ON tool_executions
        FOR EACH ROW EXECUTE FUNCTION validate_tool_execution_snapshot()
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_knowledge_chunk_scope_and_versions()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            expected_parent_kind knowledge_chunk_kind;
            expected_dense_version text;
            expected_sparse_version text;
        BEGIN
            IF NEW.chunk_kind = 'CHILD' THEN
                IF NEW.sparse_weights IS NOT NULL AND EXISTS (
                    SELECT 1
                      FROM jsonb_each(NEW.sparse_weights) AS lexical_weight
                     WHERE jsonb_typeof(lexical_weight.value) <> 'number'
                ) THEN
                    RAISE EXCEPTION 'sparse lexical weights must contain only numeric values'
                        USING ERRCODE = '23514';
                END IF;

                SELECT chunk_kind
                  INTO expected_parent_kind
                  FROM knowledge_chunks
                 WHERE organization_id = NEW.organization_id
                   AND target_system_id = NEW.target_system_id
                   AND document_version_id = NEW.document_version_id
                   AND retrieval_index_version_id = NEW.retrieval_index_version_id
                   AND id = NEW.parent_chunk_id;

                IF expected_parent_kind IS DISTINCT FROM 'PARENT' THEN
                    RAISE EXCEPTION 'child chunk must reference a parent chunk in the same scope'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.representation_status = 'READY' THEN
                    SELECT dense_version, sparse_version
                      INTO expected_dense_version, expected_sparse_version
                      FROM retrieval_index_versions
                     WHERE organization_id = NEW.organization_id
                       AND target_system_id = NEW.target_system_id
                       AND id = NEW.retrieval_index_version_id;

                    IF NEW.embedding_version IS DISTINCT FROM expected_dense_version
                       OR NEW.sparse_version IS DISTINCT FROM expected_sparse_version THEN
                        RAISE EXCEPTION 'chunk representation versions must match its retrieval index'
                            USING ERRCODE = '23514';
                    END IF;
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_validate_knowledge_chunk
        BEFORE INSERT OR UPDATE ON knowledge_chunks
        FOR EACH ROW EXECUTE FUNCTION validate_knowledge_chunk_scope_and_versions()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS trg_tool_executions_append_only ON tool_executions")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_tool_provider_bindings_lifecycle ON tool_provider_bindings"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_tool_definitions_lifecycle ON tool_definitions")
    op.execute(
        "DROP TRIGGER IF EXISTS trg_retrieval_index_versions_lifecycle ON retrieval_index_versions"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_provider_catalog_snapshots_immutable ON provider_catalog_snapshots"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_knowledge_document_versions_immutable ON knowledge_document_versions"
    )
    op.execute("DROP TRIGGER IF EXISTS trg_validate_knowledge_chunk ON knowledge_chunks")
    op.execute("DROP FUNCTION IF EXISTS validate_knowledge_chunk_scope_and_versions()")
    op.execute("DROP TRIGGER IF EXISTS trg_validate_tool_execution_snapshot ON tool_executions")
    op.execute("DROP FUNCTION IF EXISTS validate_tool_execution_snapshot()")
    op.execute("DROP FUNCTION IF EXISTS validate_versioned_contract_lifecycle()")
    op.execute("DROP FUNCTION IF EXISTS validate_retrieval_index_version_lifecycle()")
    op.execute("DROP FUNCTION IF EXISTS reject_append_only_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_knowledge_chunks_retrieval_filter", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_audit_events_scope_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(
        "uq_tool_executions_idempotency",
        table_name="tool_executions",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_tool_executions_scope_started", table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_table("knowledge_document_versions")
    op.drop_index(
        "ix_tool_provider_bindings_resolution",
        table_name="tool_provider_bindings",
        postgresql_where=sa.text("enabled"),
    )
    op.drop_table("tool_provider_bindings")
    op.drop_table("retrieval_index_versions")
    op.drop_table("provider_catalog_snapshots")
    op.drop_table("knowledge_documents")
    op.drop_table("target_systems")
    op.drop_table("tool_definitions")
    op.drop_table("organizations")
    # ### end Alembic commands ###
    for enum_name in (
        "audit_actor_type",
        "tool_execution_status",
        "representation_status",
        "structure_unit_type",
        "knowledge_chunk_kind",
        "health_scope",
        "provider_type",
        "retrieval_index_status",
        "knowledge_visibility",
        "knowledge_source_type",
        "tool_risk_level",
    ):
        op.execute(f'DROP TYPE IF EXISTS "{enum_name}"')
    op.execute("DROP EXTENSION IF EXISTS vector")
